openapi: "3.0.0"
info:
  title: Client Settings
  version: 3.0.0
servers:
  - url: 'https://api.eagleeyenetworks.com/api/v3.0/'
    description: "Eagle Eye Networks API Server"
x-readme:
  explorer-enabled: true

paths:
  /clientSettings:
    get:
      operationId: getClientSettings
      description: Your account's Base URL can be retrieved through this endpoint.
      tags:
        - ClientSettings

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiClientSettings'
        '401':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/unauthorized'
        '500':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'

components:

  schemas:

    ApiHttpsBaseUrl:
      type: object
      description: >
        Represents base URL to use to do REST API calls over https. This includes the host and port information.
      properties:
        hostname:
          type: string
          description: >
            Host to connect to do REST API calls
          example: api.c000.eagleeyenetworks.com
        port:
          type: integer
          example: 443

    ApiClientSettings:
      type: object
      properties:
        httpsBaseUrl:
          $ref: '#/components/schemas/ApiHttpsBaseUrl'

  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []