openapi: "3.0.0"
info:
  title: PTZ
  description: >
   The PTZ API provides a set of endpoints to control the position and zoom of a camera. The camera movement space is defined as pan:(-1,1), tilt:(-1,1), zoom:(0,1).  
   The cameras movement space is represented in
     the following ways:
     * pan: between -1(max left) and 1(max right)
     * tilt: between -1(max down) and 1(max up)
     * zoom: between 0(fully zoomed out) and 1(fully zoomed in)  
   The endpoints enable the client to move the camera to a specific position or to move it in a specific direction. The API provides three types of moves - position move,
   direction move, and center move. The API provides support for getting the current position of the camera and moving the camera to a specified position.
  version: 3.0.0
servers:
  - url: 'https://{BaseUrl}/api/v3.0/'
    description: "Eagle Eye Networks API Server"
x-readme:
  explorer-enabled: true

components:
  schemas:

    MoveType:
      type: string
      enum: [ position, centerOn, direction ]

    ApiPtzPosition:
      description: The ptz coordinates of the camera in a space defined as pan:(-1,1), tilt:(-1,1), zoom:(0,1).
      type: object
      properties:
        x:
          type: number
          format: double
          description: Pan coordinate given as value between -1(max left) and 1(max right).
          minimum: -1
          maximum: 1
        y:
          type: number
          format: double
          description: Tilt coordinate given as value between -1(max down) and 1(max up).
          minimum: -1
          maximum: 1
        z:
          type: number
          format: double
          description: Zoom coordinate given as value between 0(fully zoomed out) and 1(fully zoomed in).
          minimum: 0
          maximum: 1
      minProperties: 1
  

    ApiPtzPositionMove:
      description: Moves the camera to a ptz coordinate in a space defined as pan:(-1,1), tilt:(-1,1), zoom:(0,1). This move
        is normally used for moving to presets. It is not only possible to give the full x,y,z coordinates here, you can also
        either give only x,y or give only z.
      allOf:
        - $ref: '#/components/schemas/ApiPtzPosition'

    ApiPtzMove:
      type: object
      oneOf:
        - $ref: '#/components/schemas/ApiPtzCenterOnMove'
        - $ref: '#/components/schemas/ApiPtzDirectionMove'
        - $ref: '#/components/schemas/ApiPtzPositionMove'
      discriminator:
        propertyName: moveType
        mapping:
          centerOn: '#/components/schemas/ApiPtzCenterOnMove'
          direction: '#/components/schemas/ApiPtzDirectionMove'
          position: '#/components/schemas/ApiPtzPositionMove'
      properties:
        moveType:
          $ref: "#/components/schemas/MoveType"
      required:
        - moveType

    ApiPtzCenterOnMove:
      description: Move the center of the camera to the indicated(clicked) point within the shown image.
        The point is encoded as the relative x and y based on the width and height of the shown image on a
        scale from 0 to 1, where the (0,0) coordinate is top left and (1,1) is bottom right.
      properties:
        relativeX:
          type: number
          format: double
          minimum: 0
          maximum: 1
          description: relative x coordinate.
        relativeY:
          type: number
          format: double
          minimum: 0
          maximum: 1
          description: relative y coordinate.
      required: [ relativeX, relativeY ]

    ApiPtzDirectionMove:
      description: Move the camera in the given direction.
      properties:
        direction:
          description: The direction to move in.
          type: array
          minItems: 1
          maxItems: 3
          items:
            type: string
            enum: [up, down, left, right, in, out ]

        stepSize:
          description: How much we will move, if no stepSize is given then `medium` stepsize is taken.
          type: string
          enum: [ small, medium, large ]
          default: medium
      required: [ direction ]
  
  
  parameters:
    cameraId:
      name: cameraId
      in: path
      required: true
      description: ID of camera we want to operate on.
      schema:
        type: string
        pattern: ^[0-9a-f]{8}$
        example: abcdef01
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []   

paths:
  /cameras/{cameraId}/ptz/position:
    parameters:
      - $ref: "#/components/parameters/cameraId"
    get:
      operationId: getCurrentPosition
      description: >
       This endpoint returns the current position of the camera. The response includes the pan, tilt, and zoom values of the camera. If the camera does not support pan or 
       tilt or zoom, the corresponding value will not be present in the response.
      tags:
        - PTZ
      responses:
        '200':
          description: Current PTZ position of camera.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiPtzPosition"
        '400':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/validationError'
        '404':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/resourceNotFound'
        '409':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/conflict'
        '500':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'

    put:
      operationId: moveTo
      description: >
       This endpoint moves the camera to a specific position, in a specific direction, or to a specific center point on the screen.
       The endpoint accepts a move object that can be either a position move, a direction move or a center move.
      tags:
        - PTZ
      requestBody:
        description: >
         Describes where to move the camera to, this could be either a directional, center or position move object. For a position move
         its possible to only specify the zoom or the pan and tilt you want to move. Its ofcourse also possible to give all 3 coordinates.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiPtzMove"
            examples:
              Direction:
                value:
                  moveType: direction
                  direction: [ up ]
                  stepSize: large
              Position:
                value:
                  moveType: position
                  x: 0.12345
                  y: -0.98765
                  z: 0.45678
              Center:
                value:
                  moveType: center
                  relativeX: 0.3148
                  relativeY: 0.732

      responses:
        '204':
          description: Camera moved to given position.
        '400':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/validationError'
        '404':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/resourceNotFound'
        '409':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/conflict'  
        '500':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'
  
  