openapi: "3.0.0"
info:
  title: Resource Grants 
  version: 3.0.0
servers:
  - url: 'https://{BaseUrl}/api/v3.0/'
    description: "Eagle Eye Networks API Server"
x-readme:
  explorer-enabled: true

paths:
  /resourceGrants:
    get:
      operationId: getResourceGrants
      description: >
       This endpoint allows you to Retrieve a list of resource grants with pagination and filter parameters.  
         
       It is important to note that after using the pageSize parameter, the "totalSize" in the response represents 
       the total number of available devices, not the number of bridges resulting from the query string.
      tags:
        - ResourceGrants
      parameters:
        # Pagination
        - $ref: 'https://commonswagger.cameramanager.com/pagination.yaml#/components/parameters/pageToken'
        - $ref: 'https://commonswagger.cameramanager.com/pagination.yaml#/components/parameters/pageSize'

        # Filters
        - $ref: '#/components/parameters/resourceType'
        - $ref: '#/components/parameters/userId__in'
        - $ref: '#/components/parameters/resourceId__in'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPaginatedResourceGrantResponse'
        '400':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/validationError'
        '401':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/unauthorized'
        '403':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/forbidden'
        '404':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/resourceNotFound'
        '500':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'

  /resourceGrants:bulkCreate:
    post:
      operationId: createResourceGrants
      description: This endpoint allows you to create multiple resource grants in one request.
      tags:
        - ResourceGrants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceGrantsBulkCreate'
      responses:
        200:
          description: Operations performed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkResponse'
        400:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/validationError'
        401:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/unauthorized'
        403:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/forbidden'
        500:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'

  /resourceGrants:bulkDelete:
    post:
      operationId: deleteResourceGrants
      description: This endpoint allows you to delete multiple resource grants in one request.
      tags:
        - ResourceGrants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceGrantsBulkDelete'
      responses:
        200:
          description: Operations performed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkResponse'
        400:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/validationError'
        401:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/unauthorized'
        403:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/forbidden'
        500:
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'

components:
  parameters:
    resourceType:
      in: query
      name: resourceType
      description: Filter to get the grants with the specified resource type
      schema:
        $ref: '#/components/schemas/ResourceType'
      required: true

    userId__in:
      in: query
      name: userId__in
      description: Filter to get the grants whose userId is on the provided list. The lookup is exact but case insensitive
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false

    resourceId__in:
      in: query
      name: resourceId__in
      description: Filter to get the grants whose resourceId is on the provided list. The lookup is exact but case insensitive
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false

  schemas:
    ApiPaginatedResourceGrantResponse:
      allOf:
        - $ref: 'https://commonswagger.cameramanager.com/pagination.yaml#/components/schemas/PaginatedResponse'
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/ResourceGrantGet'

    ResourceType:
      type: string
      enum:
        - layout
        - camera
        - location
        - account
      example: account

    ResourceGrantOptions:
      type: object
      properties:
        expirationTimestamp:
          type: string
          format: date-time
          description: The date when access to resource ends. This can be only set for accounts.

    ResourceGrant:
      properties:
        id:
          type: string
          readOnly: true
        resourceId:
          type: string
        userId:
          type: string
        resourceType:
          $ref: '#/components/schemas/ResourceType'
        createTimestamp:
          type: string
          format: date-time
          readOnly: true
        options:
          $ref: '#/components/schemas/ResourceGrantOptions'

    ResourceGrantGet:
      allOf:
        - $ref: '#/components/schemas/ResourceGrant'
      required:
        - id
        - resourceId
        - userId
        - resourceType
        - createTimestamp
        - options

    ResourceGrantCreate:
      allOf:
        - $ref: '#/components/schemas/ResourceGrant'
      required:
        - resourceId
        - userId
        - resourceType

    ResourceGrantsBulkCreate:
      type: array
      items:
        $ref: '#/components/schemas/ResourceGrantCreate'

    ResourceGrantsBulkDelete:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/ResourceGrantCompositeId'
      required:
        - ids

    ResourceGrantCompositeId:
      type: object
      properties:
        resourceId:
          type: string
        userId:
          type: string
        resourceType:
          $ref: '#/components/schemas/ResourceType'
      required:
        - resourceId
        - userId
        - resourceType

    BulkResponse:
      type: array
      items:
        $ref: '#/components/schemas/BulkResponseItem'

    BulkResponseItem:
      type: object
      properties:
        resourceId:
          type: string
        userId:
          type: string
        resourceType:
          $ref: '#/components/schemas/ResourceType'
        status:
          type: integer
          example: 200
      required:
        - resourceId
        - userId
        - resourceType
        - status

  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []
