openapi: "3.0.0"
info:
  title: Time Zones
  version: 3.0.0
servers:
  - url: 'https://{BaseUrl}/api/v3.0/'
    description: "Eagle Eye Networks API Server"
x-readme:
  explorer-enabled: true

paths:
  /timeZones:
    get:
      operationId: listTimeZones
      description: >
        This endpint allows you to retrieve a list of the supported time zones.  
          
        It is important to note that after using the pageSize parameter, the "totalSize" 
        in the response represents the total number of available devices, not the number of bridges resulting from the query string.
      tags:
        - TimeZones
      parameters:

        # Pagination
        - $ref: 'https://commonswagger.cameramanager.com/pagination.yaml#/components/parameters/pageToken'
        - $ref: 'https://commonswagger.cameramanager.com/pagination.yaml#/components/parameters/pageSize'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTimeZoneResponse'
        '400':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/validationError'
        '401':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/unauthorized'
        '500':
          $ref: 'https://commonswagger.cameramanager.com/error.yaml#/components/responses/internalServerError'

components:

  schemas:

    PaginatedTimeZoneResponse:
      allOf:
        - $ref: 'https://commonswagger.cameramanager.com/pagination.yaml#/components/schemas/PaginatedResponse'
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/TimeZone'

    TimeZone:
      type: object
      description: >
        Represents a time zone that is supported by the Eagle Eye Networks API. Designed as an object to allow future
        extension by adding new fields.
      properties:
        name:
          type: string
          description: >
            Name of the time zone in "tz database" format of "Area/Location" us as identifier of the time zone in the
            EEN API.
          example: America/New_York
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []